Trying to fix Snap-CI
Is complaining:
/var/snap-ci/repo/node_modules/xml2json/node_modules/joi/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.

Cannot use higher than 0.12 node version...